# Generated by Django 4.0.5 on 2022-06-22 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='List_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('work', models.TextField()),
                ('setting_time', models.DateTimeField()),
                ('work_status', models.BooleanField(default=False)),
            ],
        ),
    ]
