# Generated by Django 4.0.5 on 2022-06-22 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='list_model',
            name='setting_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='list_model',
            name='setting_time',
            field=models.TimeField(null=True),
        ),
    ]
